openapi: 3.0.3
info:
  title: Product Service
  description: HTTP Product Service
  version: "1.0"
servers:
- url: http://localhost:8088
paths:
  /products:
    get:
      tags:
      - products
      summary: get_all_products products
      operationId: products#get_all_products
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: integer
                example: 5057609757035171432
                format: int64
              example: 6535090286424634345
components: {}
tags:
- name: products
  description: the product service
